# Generated by Django 5.2.2 on 2025-06-07 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sınıf Adı')),
                ('year', models.IntegerField(verbose_name='Mezuniyet Yılı')),
            ],
            options={
                'verbose_name': 'Sınıf',
                'verbose_name_plural': 'Sınıflar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profil Fotoğrafı')),
                ('bio', models.TextField(blank=True, verbose_name='Hakkında')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.schoolclass', verbose_name='Sınıfı')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İlişkili Kullanıcı')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Anı Metni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma Tarihi')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onay Durumu')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazan Kişi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='yearbook.student', verbose_name='Hakkında Yazılan Öğrenci')),
            ],
            options={
                'verbose_name': 'Anı',
                'verbose_name_plural': 'Anılar',
            },
        ),
    ]
