# Generated by Django 5.2.2 on 2025-06-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_alter_student_options_remove_student_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
    ]
