# Generated by Django 5.2.2 on 2025-06-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0003_remove_student_school_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolClass',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '2025 Dönemi Tıp fakültesi Mezunu', 'verbose_name_plural': '2025 Dönemi Tıp fakültesi Mezunları'},
        ),
        migrations.AddField(
            model_name='student',
            name='your_choise_photo',
            field=models.ImageField(blank=True, null=True, upload_to='your_choise_photo /2025/', verbose_name='Kendi Seçiminiz Fotoğrafı'),
        ),
    ]
