# Generated by Django 5.2.2 on 2025-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0004_delete_schoolclass_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='your_choise_photo',
        ),
        migrations.AddField(
            model_name='student',
            name='your_choice_photo',
            field=models.ImageField(blank=True, null=True, upload_to='your_choice_photos/2025/', verbose_name='Kendi Seçtiği Fotoğraf'),
        ),
    ]
